# Generated by Django 6.0.6 on 2026-06-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionVisiteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("derniere_activite", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredictionBesoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profil", models.CharField(max_length=100)),
                ("besoin_probable", models.CharField(max_length=255)),
                ("intention", models.CharField(max_length=50)),
                ("score", models.IntegerField(default=0)),
                ("recommandation", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="predictor.sessionvisiteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvenementUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("page_vue", "Page vue"),
                            ("clic", "Clic"),
                            ("temps", "Temps passé"),
                            ("formulaire", "Formulaire"),
                        ],
                        max_length=50,
                    ),
                ),
                ("page", models.CharField(max_length=255)),
                ("valeur", models.CharField(blank=True, max_length=255, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="predictor.sessionvisiteur",
                    ),
                ),
            ],
        ),
    ]
