# Generated by Django 6.0.6 on 2026-06-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0002_clientprofessionnel_siteclient_sessionvisiteur_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenementutilisateur",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("page_vue", "Page vue"),
                    ("clic", "Clic"),
                    ("temps", "Temps passé"),
                    ("formulaire", "Formulaire"),
                    ("lead", "Lead capturé"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="LeadCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("profil", models.CharField(blank=True, max_length=100, null=True)),
                ("intention", models.CharField(blank=True, max_length=50, null=True)),
                ("score", models.IntegerField(default=0)),
                ("consentement", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="predictor.sessionvisiteur",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="predictor.siteclient",
                    ),
                ),
            ],
        ),
    ]
