# Generated by Django 6.0.6 on 2026-06-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0003_alter_evenementutilisateur_type_evenement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadcapture",
            name="statut_suivi",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("contacte", "Contacté"),
                    ("converti", "Converti"),
                    ("perdu", "Perdu"),
                ],
                default="nouveau",
                max_length=30,
            ),
        ),
    ]
