# Generated by Django 6.0.6 on 2026-06-23 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0004_leadcapture_statut_suivi"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportuniteCRM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "montant_estime",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "etape",
                    models.CharField(
                        choices=[
                            ("qualification", "Qualification"),
                            ("proposition", "Proposition envoyée"),
                            ("negociation", "Négociation"),
                            ("gagne", "Gagné"),
                            ("perdu", "Perdu"),
                        ],
                        default="qualification",
                        max_length=30,
                    ),
                ),
                ("probabilite", models.IntegerField(default=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunites",
                        to="predictor.leadcapture",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunites",
                        to="predictor.siteclient",
                    ),
                ),
            ],
        ),
    ]
