# Generated by Django 6.0.6 on 2026-07-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0005_opportunitecrm"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionvisiteur",
            name="appareil",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="est_desktop",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="est_mobile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="est_rebond",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="est_tablette",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="navigateur",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="nombre_clics",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="nombre_pages_vues",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="referer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="source_visite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="systeme_exploitation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="temps_total_secondes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="sessionvisiteur",
            name="utm_source",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
