# Generated by Django 6.0.6 on 2026-07-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "predictor",
            "0006_sessionvisiteur_appareil_sessionvisiteur_est_desktop_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteclient",
            name="module_ecommerce_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="type_site",
            field=models.CharField(
                choices=[
                    ("vitrine", "Site vitrine"),
                    ("formation", "Centre de formation"),
                    ("service_b2b", "Service B2B"),
                    ("coach", "Coach / Consultant"),
                    ("ecommerce", "E-commerce"),
                    ("immobilier", "Immobilier"),
                    ("beaute", "Beauté / Esthétique"),
                ],
                default="vitrine",
                max_length=30,
            ),
        ),
    ]
