# Generated by Django 6.0.6 on 2026-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0007_siteclient_module_ecommerce_actif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteclient",
            name="module_connecteurs_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="module_historique_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="module_multicanal_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="module_prediction_avancee_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="module_publicite_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="module_securite_entreprise_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="module_segmentation_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="module_visualisations_actif",
            field=models.BooleanField(default=False),
        ),
    ]
