# Generated by Codex on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0008_siteclient_module_connecteurs_actif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofessionnel",
            name="plan_abonnement",
            field=models.CharField(default="predictneed_pro", max_length=80),
        ),
        migrations.AddField(
            model_name="clientprofessionnel",
            name="statut_abonnement",
            field=models.CharField(
                choices=[
                    ("paiement_en_attente", "Paiement en attente"),
                    ("actif", "Actif"),
                    ("essai", "Essai"),
                    ("impaye", "Impayé"),
                    ("annule", "Annulé"),
                ],
                default="actif",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="clientprofessionnel",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="clientprofessionnel",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="clientprofessionnel",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="clientprofessionnel",
            name="date_acceptation_cgu",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofessionnel",
            name="date_activation_abonnement",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
