# Generated by Codex on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0009_clientprofessionnel_abonnement"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomatisationEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nom",
                    models.CharField(default="Confirmation de demande", max_length=180),
                ),
                (
                    "type_declencheur",
                    models.CharField(
                        choices=[
                            ("lead_confirmation", "Confirmation automatique de demande"),
                        ],
                        default="lead_confirmation",
                        max_length=60,
                    ),
                ),
                (
                    "sujet",
                    models.CharField(
                        default="Votre demande a bien été enregistrée",
                        max_length=220,
                    ),
                ),
                (
                    "contenu",
                    models.TextField(
                        default=(
                            "Bonjour {nom},\n\n"
                            "Votre demande a bien été enregistrée par {entreprise}. "
                            "Nous reviendrons vers vous rapidement.\n\n"
                            "Message reçu : {message}\n\n"
                            "À bientôt,\n"
                            "{entreprise}"
                        ),
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("envoyer_copie_interne", models.BooleanField(default=False)),
                ("email_copie", models.EmailField(blank=True, max_length=254, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automatisations_email",
                        to="predictor.clientprofessionnel",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automatisations_email",
                        to="predictor.siteclient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailAutomatise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("destinataire", models.EmailField(blank=True, max_length=254, null=True)),
                ("sujet", models.CharField(max_length=220)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoye", "Envoyé"),
                            ("erreur", "Erreur"),
                            ("ignore", "Ignoré"),
                        ],
                        default="envoye",
                        max_length=20,
                    ),
                ),
                ("erreur", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "automatisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_envoyes",
                        to="predictor.automatisationemail",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails_automatises",
                        to="predictor.leadcapture",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails_automatises",
                        to="predictor.siteclient",
                    ),
                ),
            ],
        ),
    ]
