# Generated by Codex on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0010_automatisations_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteConnecteExterne",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "plateforme",
                    models.CharField(
                        choices=[
                            ("google_ads", "Google Ads"),
                            ("meta_ads", "Meta Ads"),
                            ("linkedin_ads", "LinkedIn Ads"),
                            ("tiktok_ads", "TikTok Ads"),
                        ],
                        max_length=40,
                    ),
                ),
                ("nom_compte", models.CharField(max_length=180)),
                ("identifiant_externe", models.CharField(blank=True, max_length=180, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("configuration_requise", "Configuration requise"),
                            ("connecte", "Connecté"),
                            ("erreur", "Erreur"),
                            ("deconnecte", "Déconnecté"),
                        ],
                        default="configuration_requise",
                        max_length=40,
                    ),
                ),
                ("scopes", models.TextField(blank=True, null=True)),
                ("access_token_signe", models.TextField(blank=True, null=True)),
                ("refresh_token_signe", models.TextField(blank=True, null=True)),
                ("token_type", models.CharField(blank=True, max_length=40, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("dernier_message", models.TextField(blank=True, null=True)),
                ("derniere_synchro", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comptes_externes",
                        to="predictor.clientprofessionnel",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comptes_externes",
                        to="predictor.siteclient",
                    ),
                ),
            ],
            options={
                "ordering": ["plateforme", "-date_mise_a_jour"],
            },
        ),
        migrations.CreateModel(
            name="CampagneExterne",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "plateforme",
                    models.CharField(
                        choices=[
                            ("google_ads", "Google Ads"),
                            ("meta_ads", "Meta Ads"),
                            ("linkedin_ads", "LinkedIn Ads"),
                            ("tiktok_ads", "TikTok Ads"),
                        ],
                        max_length=40,
                    ),
                ),
                ("identifiant_externe", models.CharField(blank=True, max_length=180, null=True)),
                ("nom", models.CharField(max_length=220)),
                ("statut", models.CharField(blank=True, max_length=80, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=150, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=150, null=True)),
                ("utm_campaign", models.CharField(blank=True, max_length=150, null=True)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clics", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("depense", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("devise", models.CharField(default="EUR", max_length=12)),
                ("donnees_brutes", models.JSONField(blank=True, default=dict)),
                ("derniere_synchro", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes",
                        to="predictor.compteconnecteexterne",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campagnes_externes",
                        to="predictor.siteclient",
                    ),
                ),
            ],
            options={
                "ordering": ["-derniere_synchro", "nom"],
            },
        ),
        migrations.CreateModel(
            name="JournalSynchronisationConnecteur",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("succes", "Succès"),
                            ("erreur", "Erreur"),
                            ("ignore", "Ignoré"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journaux_synchro",
                        to="predictor.compteconnecteexterne",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddConstraint(
            model_name="campagneexterne",
            constraint=models.UniqueConstraint(
                condition=models.Q(identifiant_externe__isnull=False),
                fields=("compte", "identifiant_externe"),
                name="campagne_externe_unique_par_compte",
            ),
        ),
    ]
