# Generated by Codex on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_STEPS = [
    (
        1,
        "Confirmation immédiate",
        0,
        "Votre demande a bien été enregistrée",
        (
            "Bonjour {nom},\n\n"
            "Votre demande a bien été enregistrée par {entreprise}. "
            "Nous reviendrons vers vous rapidement.\n\n"
            "Message reçu : {message}\n\n"
            "À bientôt,\n"
            "{entreprise}"
        ),
    ),
    (
        2,
        "Relance douce",
        2,
        "Souhaitez-vous compléter votre demande ?",
        (
            "Bonjour {nom},\n\n"
            "Nous revenons vers vous au sujet de votre demande transmise à {entreprise}. "
            "Si votre besoin est toujours d'actualité, vous pouvez répondre directement à ce message "
            "avec vos disponibilités ou les précisions utiles.\n\n"
            "À bientôt,\n"
            "{entreprise}"
        ),
    ),
    (
        3,
        "Relance valeur",
        5,
        "Votre projet est-il toujours d'actualité ?",
        (
            "Bonjour {nom},\n\n"
            "Votre demande semble liée à : {profil}. "
            "Pour vous aider à avancer, l'étape la plus utile est souvent de clarifier le besoin, "
            "le délai et le résultat attendu.\n\n"
            "Vous pouvez répondre à ce message pour nous dire où vous en êtes.\n\n"
            "{entreprise}"
        ),
    ),
    (
        4,
        "Dernière relance",
        10,
        "Dernière relance concernant votre demande",
        (
            "Bonjour {nom},\n\n"
            "Nous n'avons pas encore eu de retour concernant votre demande. "
            "Si elle est toujours d'actualité, vous pouvez répondre à cet email. "
            "Dans le cas contraire, aucune action n'est nécessaire.\n\n"
            "Bien cordialement,\n"
            "{entreprise}"
        ),
    ),
]


def creer_etapes_par_defaut(apps, schema_editor):
    AutomatisationEmail = apps.get_model("predictor", "AutomatisationEmail")
    EtapeAutomatisationEmail = apps.get_model("predictor", "EtapeAutomatisationEmail")

    for automatisation in AutomatisationEmail.objects.all():
        for ordre, nom, delai_jours, sujet, contenu in DEFAULT_STEPS:
            EtapeAutomatisationEmail.objects.get_or_create(
                automatisation=automatisation,
                ordre=ordre,
                defaults={
                    "nom": nom,
                    "delai_jours": delai_jours,
                    "sujet": sujet,
                    "contenu": contenu,
                    "actif": True,
                    "stopper_si_lead_traite": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0011_connecteurs_externes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapeAutomatisationEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordre", models.PositiveIntegerField(default=1)),
                ("nom", models.CharField(max_length=180)),
                ("delai_jours", models.PositiveIntegerField(default=0)),
                ("sujet", models.CharField(max_length=220)),
                ("contenu", models.TextField()),
                ("actif", models.BooleanField(default=True)),
                ("stopper_si_lead_traite", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "automatisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="predictor.automatisationemail",
                    ),
                ),
            ],
            options={
                "ordering": ["automatisation", "ordre"],
                "unique_together": {("automatisation", "ordre")},
            },
        ),
        migrations.AddField(
            model_name="emailautomatise",
            name="date_envoi",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailautomatise",
            name="date_programmee",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailautomatise",
            name="numero_etape",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailautomatise",
            name="etape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails_envoyes",
                to="predictor.etapeautomatisationemail",
            ),
        ),
        migrations.RunPython(creer_etapes_par_defaut, migrations.RunPython.noop),
    ]
