# Generated by Django 6.0.6 on 2026-07-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0012_etapes_automatisation_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteclient",
            name="google_ads_conversion_label",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="google_ads_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="linkedin_partner_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="linkedin_conversion_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="meta_pixel_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="pinterest_tag_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="retargeting_actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="tiktok_pixel_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
