# Generated by Django 6.0.6 on 2026-08-17 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0012_etapes_automatisation_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProspectPilotAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("landing_url", models.CharField(blank=True, max_length=2000)),
                ("utm_source", models.CharField(blank=True, max_length=150)),
                ("utm_medium", models.CharField(blank=True, max_length=150)),
                ("utm_campaign", models.CharField(blank=True, max_length=150)),
                ("utm_content", models.CharField(blank=True, max_length=150)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("product_visited_sent", models.BooleanField(default=False)),
                ("simulator_started_sent", models.BooleanField(default=False)),
                ("signup_completed_sent", models.BooleanField(default=False)),
                ("checkout_started_sent", models.BooleanField(default=False)),
                (
                    "client_professionnel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospectpilot_attributions",
                        to="predictor.clientprofessionnel",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="ProspectPilotOutboundEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(db_index=True, max_length=180, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=40)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sending", "Envoi en cours"),
                            ("sent", "Envoyé"),
                            ("failed", "Échec (nouvel essai prévu)"),
                            ("dead_letter", "Abandonné"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_events",
                        to="predictor.prospectpilotattribution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
