# Generated by Django 6.0.6 on 2026-08-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0013_siteclient_google_ads_conversion_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteclient",
            name="derniere_detection_script",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteclient",
            name="script_installe_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
