# Generated by Django 6.0.6 on 2026-08-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0013_prospectpilotattribution_prospectpilotoutboundevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospectpilotoutboundevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("sending", "Envoi en cours"),
                    ("sent", "Envoyé"),
                    ("failed", "Échec (nouvel essai prévu)"),
                    ("pending_config", "En attente de configuration"),
                    ("dead_letter", "Abandonné"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
