"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import importlib.util
from urllib.parse import urlparse, unquote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    os.environ.get(
        "SECRET_KEY",
        "django-insecure-local-development-key-predictneed-ia-change-before-production"
    )
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "predictneed-ia.fly.dev,predictneed-ia.com,www.predictneed-ia.com",
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://predictneed-ia.fly.dev,https://predictneed-ia.com,https://www.predictneed-ia.com",
    ).split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'predictor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "predictor.domain_redirect_middleware.CanonicalDomainRedirectMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if importlib.util.find_spec("whitenoise"):
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


def database_from_url(database_url):
    parsed = urlparse(database_url)
    query_options = {}

    if parsed.query:
        for item in parsed.query.split("&"):
            if "=" in item:
                key, value = item.split("=", 1)
                query_options[key] = value

    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or 5432),
        "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
    }

    if query_options.get("sslmode"):
        config["OPTIONS"] = {"sslmode": query_options["sslmode"]}

    return config


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": database_from_url(os.environ["DATABASE_URL"])
    }
elif os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

if importlib.util.find_spec("whitenoise"):
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

LOGIN_URL = '/connexion/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

PREDICTNEED_SITE_URL = os.environ.get("PREDICTNEED_SITE_URL", "").rstrip("/")
PREDICTNEED_SUBSCRIPTION_NAME = os.environ.get(
    "PREDICTNEED_SUBSCRIPTION_NAME",
    "PredictNeed IA Pro"
)
PREDICTNEED_SUBSCRIPTION_PRICE_CENTS = int(
    os.environ.get("PREDICTNEED_SUBSCRIPTION_PRICE_CENTS", "9900")
)
PREDICTNEED_SUBSCRIPTION_CURRENCY = os.environ.get(
    "PREDICTNEED_SUBSCRIPTION_CURRENCY",
    "eur"
)
PREDICTNEED_SUBSCRIPTION_INTERVAL = os.environ.get(
    "PREDICTNEED_SUBSCRIPTION_INTERVAL",
    "month"
)
PREDICTNEED_SUBSCRIPTION_TRIAL_DAYS = int(
    os.environ.get("PREDICTNEED_SUBSCRIPTION_TRIAL_DAYS", "60")
)
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PRICE_ID = os.environ.get("STRIPE_PRICE_ID", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_AUTOMATIC_TAX = os.environ.get("STRIPE_AUTOMATIC_TAX", "False") == "True"

EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False") == "True"
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "PredictNeed IA <no-reply@predictneed.local>"
)
PREDICTNEED_CONTACT_EMAIL = os.environ.get("PREDICTNEED_CONTACT_EMAIL", "")

PREDICTNEED_EXTERNAL_CONNECTORS = {
    "google_ads": {
        "nom": "Google Ads",
        "description": "Connexion OAuth pour lire les comptes et campagnes Google Ads autorisés.",
        "client_id": os.environ.get("GOOGLE_ADS_CLIENT_ID", ""),
        "client_secret": os.environ.get("GOOGLE_ADS_CLIENT_SECRET", ""),
        "developer_token": os.environ.get("GOOGLE_ADS_DEVELOPER_TOKEN", ""),
        "login_customer_id": os.environ.get("GOOGLE_ADS_LOGIN_CUSTOMER_ID", ""),
        "variables_requises": [
            "GOOGLE_ADS_CLIENT_ID",
            "GOOGLE_ADS_CLIENT_SECRET",
        ],
        "variables_optionnelles": [
            "GOOGLE_ADS_DEVELOPER_TOKEN",
            "GOOGLE_ADS_LOGIN_CUSTOMER_ID",
        ],
        "auth_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/adwords"],
        "extra_auth_params": {
            "access_type": "offline",
            "prompt": "consent",
        },
    },
    "meta_ads": {
        "nom": "Meta Ads",
        "description": "Connexion OAuth pour rapprocher Facebook Ads et Instagram Ads des leads.",
        "client_id": os.environ.get("META_ADS_CLIENT_ID", ""),
        "client_secret": os.environ.get("META_ADS_CLIENT_SECRET", ""),
        "auth_url": os.environ.get(
            "META_ADS_AUTH_URL",
            "https://www.facebook.com/v20.0/dialog/oauth",
        ),
        "token_url": os.environ.get(
            "META_ADS_TOKEN_URL",
            "https://graph.facebook.com/v20.0/oauth/access_token",
        ),
        "variables_requises": [
            "META_ADS_CLIENT_ID",
            "META_ADS_CLIENT_SECRET",
        ],
        "variables_optionnelles": [
            "META_ADS_AUTH_URL",
            "META_ADS_TOKEN_URL",
        ],
        "scopes": ["ads_read", "business_management"],
    },
    "linkedin_ads": {
        "nom": "LinkedIn Ads",
        "description": "Connexion OAuth pour lire les campagnes LinkedIn autorisées.",
        "client_id": os.environ.get("LINKEDIN_ADS_CLIENT_ID", ""),
        "client_secret": os.environ.get("LINKEDIN_ADS_CLIENT_SECRET", ""),
        "variables_requises": [
            "LINKEDIN_ADS_CLIENT_ID",
            "LINKEDIN_ADS_CLIENT_SECRET",
        ],
        "auth_url": "https://www.linkedin.com/oauth/v2/authorization",
        "token_url": "https://www.linkedin.com/oauth/v2/accessToken",
        "scopes": ["r_ads", "r_ads_reporting"],
    },
    "tiktok_ads": {
        "nom": "TikTok Ads",
        "description": "Connexion OAuth configurable pour les comptes TikTok Ads.",
        "client_id": os.environ.get("TIKTOK_ADS_CLIENT_ID", ""),
        "client_secret": os.environ.get("TIKTOK_ADS_CLIENT_SECRET", ""),
        "auth_url": os.environ.get("TIKTOK_ADS_AUTH_URL", ""),
        "token_url": os.environ.get("TIKTOK_ADS_TOKEN_URL", ""),
        "variables_requises": [
            "TIKTOK_ADS_CLIENT_ID",
            "TIKTOK_ADS_CLIENT_SECRET",
            "TIKTOK_ADS_AUTH_URL",
            "TIKTOK_ADS_TOKEN_URL",
        ],
        "variables_optionnelles": [
            "TIKTOK_ADS_SCOPES",
        ],
        "scopes": [
            scope
            for scope in os.environ.get("TIKTOK_ADS_SCOPES", "advertiser.read").split(",")
            if scope
        ],
    },
}

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    SECURE_HSTS_SECONDS = int(
        os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000")
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
        "False"
    ) == "True"
    SECURE_HSTS_PRELOAD = os.environ.get(
        "DJANGO_SECURE_HSTS_PRELOAD",
        "False"
    ) == "True"
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0

# Hôtes autorisés pour le développement local
for _local_host in ("127.0.0.1", "localhost"):
    if _local_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_local_host)
